### ISSUE TITLE
Pin version to `0.5.1-d-build.1161`

### ISSUE THREAD

**Issue by solonovamax** [EthanRStokes/Create#14] opened 2023-12-07 00:51 UTC
### Describe the Bug

Currently, the version that the mod uses is `0.5.1-d-build.5`. However, some mods *specifically* depend on version `0.5.1-d-build.1161` (the latest release). It would be good if the build number could be pinned to `1161`.

### Reproduction Steps

1. Install the fork
2. Install a mod such as [Create: SandPaper Overhaul](https://modrinth.com/mod/create-sandpaper-overhaul)
3. Cannot launch game due to Create: SandPaper Overhaul requiring *specifically* create version `0.5.1-d-build.1161`

### Expected Result

Game launches.

### Screenshots and Videos

N/A

### Crash Report or Log

N/A

### Operating System

Linux

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

https://modrinth.com/mod/create-sandpaper-overhaul, N/A

### Additional Context

N/A

**Comment by solonovamax** [comment] 2023-12-07 00:52
I am temporary fixing this for myself, via the following patch:
```diff
diff --git a/build.gradle b/build.gradle
index a83006992..7d834c3ca 100644
--- a/build.gradle
+++ b/build.gradle
@@ -13,8 +13,9 @@ plugins {
 sourceCompatibility = JavaVersion.VERSION_17
 targetCompatibility = JavaVersion.VERSION_17
 
-String runNumber = System.getenv("GITHUB_RUN_NUMBER")
-String build = runNumber != null ? "build.$runNumber" : "local"
+// String runNumber = System.getenv("GITHUB_RUN_NUMBER")
+String build = "build.1161"
+// String build = runNumber != null ? "build.$runNumber" : "local"
 version = "$mod_version-$build+mc$minecraft_version"
 
 group = project.maven_group
```

**Comment by raws** [comment] 2023-12-07 03:39
Looks like this affects [Create Deco Fabric 2.0.0+1.20.1](https://www.curseforge.com/minecraft/mc-mods/create-deco-fabric/files/4931869) as well. Confirmed that your patch fixes it. (Though instead of changing `build.gradle`, I just set `GITHUB_RUN_NUMBER` at build time, which works great locally, but wouldn't work with GitHub Actions due to [default environment variable precedence](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables).)

**Comment by solonovamax** [comment] 2023-12-08 03:57
Yes, create deco is another one that I ran into which relied on the build number.

I set it in the buildscript, as that's technically the """better solution""", but whatever (tho the real better solution would be for mods to not depend on the build number lmao)

**Comment by AsgerJon** [comment] 2023-12-09 11:15
Also Create Air Fabric has this error.

**Comment by ryouzue** [comment] 2024-01-10 17:27
Any news about a better fix yet (besides the earlier patch)? It's been over a month since this issue opened

**Comment by crabinpenguin** [comment] 2024-01-15 09:13
Would it be too much trouble to provide an explanation as to how to implement this patch? @solonovamax 
I'd love to do this but I am not sure how.

> I am temporary fixing this for myself, via the following patch:
> 
> ```diff
> diff --git a/build.gradle b/build.gradle
> index a83006992..7d834c3ca 100644
> --- a/build.gradle
> +++ b/build.gradle
> @@ -13,8 +13,9 @@ plugins {
>  sourceCompatibility = JavaVersion.VERSION_17
>  targetCompatibility = JavaVersion.VERSION_17
>  
> -String runNumber = System.getenv("GITHUB_RUN_NUMBER")
> -String build = runNumber != null ? "build.$runNumber" : "local"
> +// String runNumber = System.getenv("GITHUB_RUN_NUMBER")
> +String build = "build.1161"
> +// String build = runNumber != null ? "build.$runNumber" : "local"
>  version = "$mod_version-$build+mc$minecraft_version"
>  
>  group = project.maven_group
> ```

**Comment by Poopooracoocoo** [comment] 2024-01-16 18:53
@corbinpenguin I recommend just using a Fabric Dependency Override. Example: https://github.com/talrey/CreateDeco/issues/105#issuecomment-1860003640

**Comment by solonovamax** [comment] 2024-01-16 19:04
> Would it be too much trouble to provide an explanation as to how to implement this patch? @solonovamax 
> I'd love to do this but I am not sure how.
> 
> > I am temporary fixing this for myself, via the following patch:
> > 
> > ```diff
> > diff --git a/build.gradle b/build.gradle
> > index a83006992..7d834c3ca 100644
> > --- a/build.gradle
> > +++ b/build.gradle
> > @@ -13,8 +13,9 @@ plugins {
> >  sourceCompatibility = JavaVersion.VERSION_17
> >  targetCompatibility = JavaVersion.VERSION_17
> >  
> > -String runNumber = System.getenv("GITHUB_RUN_NUMBER")
> > -String build = runNumber != null ? "build.$runNumber" : "local"
> > +// String runNumber = System.getenv("GITHUB_RUN_NUMBER")
> > +String build = "build.1161"
> > +// String build = runNumber != null ? "build.$runNumber" : "local"
> >  version = "$mod_version-$build+mc$minecraft_version"
> >  
> >  group = project.maven_group
> > ```
> 
> 

either use the dependency override (as suggested by @Poopooracoocoo), or follow [these instructions](https://github.com/Globox1997/tiered/issues/88#issuecomment-1843497489)

**Comment by mucookul** [comment] 2024-01-26 23:46
I made a build of it: https://github.com/Mukul1127/Create-Sodium-Fix

**Comment by NEPTUNE2345** [comment] 2024-01-28 17:39
> I made a build of it: https://github.com/Mukul1127/Create-Sodium-Fix

doesn't work :(

**Comment by EthanRStokes** [comment] 2024-02-18 23:25
fixed in latest update

**Closed as completed by EthanRStokes** 2024-02-18 23:25 UTC
Labels: bug
